/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiEndpointsJobsCreateReq,
  ApiEndpointsJobsCreateRes,
  ApiEndpointsJobsGetByIdRes,
  ApiEndpointsJobsListRes,
  ApiEndpointsJobsRenameReq,
} from '../models';

export interface ApiEndpointsJobsCreateRequest {
    apiEndpointsJobsCreateReq: ApiEndpointsJobsCreateReq;
}

export interface ApiEndpointsJobsDeleteRequest {
    id: number;
}

export interface ApiEndpointsJobsGetByIdRequest {
    id: number;
}

export interface ApiEndpointsJobsRenameRequest {
    id: number;
    apiEndpointsJobsRenameReq: ApiEndpointsJobsRenameReq;
}

/**
 * 
 */
export class JobsApi extends runtime.BaseAPI {

    /**
     */
    async apiEndpointsJobsCreateRaw(requestParameters: ApiEndpointsJobsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiEndpointsJobsCreateRes>> {
        if (requestParameters.apiEndpointsJobsCreateReq === null || requestParameters.apiEndpointsJobsCreateReq === undefined) {
            throw new runtime.RequiredError('apiEndpointsJobsCreateReq','Required parameter requestParameters.apiEndpointsJobsCreateReq was null or undefined when calling apiEndpointsJobsCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/jobs`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.apiEndpointsJobsCreateReq,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async apiEndpointsJobsCreate(requestParameters: ApiEndpointsJobsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEndpointsJobsCreateRes> {
        const response = await this.apiEndpointsJobsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiEndpointsJobsDeleteRaw(requestParameters: ApiEndpointsJobsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiEndpointsJobsDelete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/jobs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiEndpointsJobsDelete(requestParameters: ApiEndpointsJobsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.apiEndpointsJobsDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiEndpointsJobsGetByIdRaw(requestParameters: ApiEndpointsJobsGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiEndpointsJobsGetByIdRes>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiEndpointsJobsGetById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/jobs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async apiEndpointsJobsGetById(requestParameters: ApiEndpointsJobsGetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiEndpointsJobsGetByIdRes> {
        const response = await this.apiEndpointsJobsGetByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiEndpointsJobsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiEndpointsJobsListRes>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/jobs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     */
    async apiEndpointsJobsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiEndpointsJobsListRes>> {
        const response = await this.apiEndpointsJobsListRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiEndpointsJobsRenameRaw(requestParameters: ApiEndpointsJobsRenameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling apiEndpointsJobsRename.');
        }

        if (requestParameters.apiEndpointsJobsRenameReq === null || requestParameters.apiEndpointsJobsRenameReq === undefined) {
            throw new runtime.RequiredError('apiEndpointsJobsRenameReq','Required parameter requestParameters.apiEndpointsJobsRenameReq was null or undefined when calling apiEndpointsJobsRename.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/jobs/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.apiEndpointsJobsRenameReq,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async apiEndpointsJobsRename(requestParameters: ApiEndpointsJobsRenameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.apiEndpointsJobsRenameRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
