/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DetectorCommandDetectorCommand } from './DetectorCommandDetectorCommand';
import {
    DetectorCommandDetectorCommandFromJSON,
    DetectorCommandDetectorCommandFromJSONTyped,
    DetectorCommandDetectorCommandToJSON,
} from './DetectorCommandDetectorCommand';

/**
 * 
 * @export
 * @interface DetectorsCommandReq
 */
export interface DetectorsCommandReq {
    /**
     * 
     * @type {DetectorCommandDetectorCommand}
     * @memberof DetectorsCommandReq
     */
    command?: DetectorCommandDetectorCommand;
}

/**
 * Check if a given object implements the DetectorsCommandReq interface.
 */
export function instanceOfDetectorsCommandReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetectorsCommandReqFromJSON(json: any): DetectorsCommandReq {
    return DetectorsCommandReqFromJSONTyped(json, false);
}

export function DetectorsCommandReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectorsCommandReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'command': !exists(json, 'Command') ? undefined : DetectorCommandDetectorCommandFromJSON(json['Command']),
    };
}

export function DetectorsCommandReqToJSON(value?: DetectorsCommandReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Command': DetectorCommandDetectorCommandToJSON(value.command),
    };
}

