/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetectorCommandDetectorCommand
 */
export interface DetectorCommandDetectorCommand {
    /**
     * 
     * @type {boolean}
     * @memberof DetectorCommandDetectorCommand
     */
    isRestart?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DetectorCommandDetectorCommand
     */
    isStartDetection?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DetectorCommandDetectorCommand
     */
    isStopDetection?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DetectorCommandDetectorCommand
     */
    isResumeDetection?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DetectorCommandDetectorCommand
     */
    isPauseDetection?: boolean;
}

/**
 * Check if a given object implements the DetectorCommandDetectorCommand interface.
 */
export function instanceOfDetectorCommandDetectorCommand(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetectorCommandDetectorCommandFromJSON(json: any): DetectorCommandDetectorCommand {
    return DetectorCommandDetectorCommandFromJSONTyped(json, false);
}

export function DetectorCommandDetectorCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectorCommandDetectorCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isRestart': !exists(json, 'IsRestart') ? undefined : json['IsRestart'],
        'isStartDetection': !exists(json, 'IsStartDetection') ? undefined : json['IsStartDetection'],
        'isStopDetection': !exists(json, 'IsStopDetection') ? undefined : json['IsStopDetection'],
        'isResumeDetection': !exists(json, 'IsResumeDetection') ? undefined : json['IsResumeDetection'],
        'isPauseDetection': !exists(json, 'IsPauseDetection') ? undefined : json['IsPauseDetection'],
    };
}

export function DetectorCommandDetectorCommandToJSON(value?: DetectorCommandDetectorCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'IsRestart': value.isRestart,
        'IsStartDetection': value.isStartDetection,
        'IsStopDetection': value.isStopDetection,
        'IsResumeDetection': value.isResumeDetection,
        'IsPauseDetection': value.isPauseDetection,
    };
}

