/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetectorsHeartBeatReq
 */
export interface DetectorsHeartBeatReq {
    /**
     * 
     * @type {number}
     * @memberof DetectorsHeartBeatReq
     */
    temperature?: number;
    /**
     * 
     * @type {number}
     * @memberof DetectorsHeartBeatReq
     */
    freeStoragePercentage?: number;
    /**
     * 
     * @type {number}
     * @memberof DetectorsHeartBeatReq
     */
    uptime?: number;
}

/**
 * Check if a given object implements the DetectorsHeartBeatReq interface.
 */
export function instanceOfDetectorsHeartBeatReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetectorsHeartBeatReqFromJSON(json: any): DetectorsHeartBeatReq {
    return DetectorsHeartBeatReqFromJSONTyped(json, false);
}

export function DetectorsHeartBeatReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectorsHeartBeatReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'temperature': !exists(json, 'Temperature') ? undefined : json['Temperature'],
        'freeStoragePercentage': !exists(json, 'FreeStoragePercentage') ? undefined : json['FreeStoragePercentage'],
        'uptime': !exists(json, 'Uptime') ? undefined : json['Uptime'],
    };
}

export function DetectorsHeartBeatReqToJSON(value?: DetectorsHeartBeatReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Temperature': value.temperature,
        'FreeStoragePercentage': value.freeStoragePercentage,
        'Uptime': value.uptime,
    };
}

