/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DetectorsIdentifyReqCalibrationCoordsReq
 */
export interface DetectorsIdentifyReqCalibrationCoordsReq {
    /**
     * 
     * @type {number}
     * @memberof DetectorsIdentifyReqCalibrationCoordsReq
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof DetectorsIdentifyReqCalibrationCoordsReq
     */
    y?: number;
}

/**
 * Check if a given object implements the DetectorsIdentifyReqCalibrationCoordsReq interface.
 */
export function instanceOfDetectorsIdentifyReqCalibrationCoordsReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DetectorsIdentifyReqCalibrationCoordsReqFromJSON(json: any): DetectorsIdentifyReqCalibrationCoordsReq {
    return DetectorsIdentifyReqCalibrationCoordsReqFromJSONTyped(json, false);
}

export function DetectorsIdentifyReqCalibrationCoordsReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): DetectorsIdentifyReqCalibrationCoordsReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': !exists(json, 'X') ? undefined : json['X'],
        'y': !exists(json, 'Y') ? undefined : json['Y'],
    };
}

export function DetectorsIdentifyReqCalibrationCoordsReqToJSON(value?: DetectorsIdentifyReqCalibrationCoordsReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'X': value.x,
        'Y': value.y,
    };
}

