/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventsCreateReq
 */
export interface EventsCreateReq {
    /**
     * 
     * @type {number}
     * @memberof EventsCreateReq
     */
    taskId?: number;
    /**
     * 
     * @type {number}
     * @memberof EventsCreateReq
     */
    stepId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EventsCreateReq
     */
    eventResult?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EventsCreateReq
     */
    failureReason?: string;
}

/**
 * Check if a given object implements the EventsCreateReq interface.
 */
export function instanceOfEventsCreateReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EventsCreateReqFromJSON(json: any): EventsCreateReq {
    return EventsCreateReqFromJSONTyped(json, false);
}

export function EventsCreateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventsCreateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskId': !exists(json, 'TaskId') ? undefined : json['TaskId'],
        'stepId': !exists(json, 'StepId') ? undefined : json['StepId'],
        'eventResult': !exists(json, 'EventResult') ? undefined : json['EventResult'],
        'failureReason': !exists(json, 'FailureReason') ? undefined : json['FailureReason'],
    };
}

export function EventsCreateReqToJSON(value?: EventsCreateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TaskId': value.taskId,
        'StepId': value.stepId,
        'EventResult': value.eventResult,
        'FailureReason': value.failureReason,
    };
}

