/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobsCreateReq
 */
export interface JobsCreateReq {
    /**
     * 
     * @type {string}
     * @memberof JobsCreateReq
     */
    name?: string;
}

/**
 * Check if a given object implements the JobsCreateReq interface.
 */
export function instanceOfJobsCreateReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JobsCreateReqFromJSON(json: any): JobsCreateReq {
    return JobsCreateReqFromJSONTyped(json, false);
}

export function JobsCreateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsCreateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function JobsCreateReqToJSON(value?: JobsCreateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
    };
}

