/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobsRenameReq
 */
export interface JobsRenameReq {
    /**
     * 
     * @type {string}
     * @memberof JobsRenameReq
     */
    name?: string;
}

/**
 * Check if a given object implements the JobsRenameReq interface.
 */
export function instanceOfJobsRenameReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JobsRenameReqFromJSON(json: any): JobsRenameReq {
    return JobsRenameReqFromJSONTyped(json, false);
}

export function JobsRenameReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsRenameReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function JobsRenameReqToJSON(value?: JobsRenameReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
    };
}

