/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LinesCreateReq
 */
export interface LinesCreateReq {
    /**
     * 
     * @type {string}
     * @memberof LinesCreateReq
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof LinesCreateReq
     */
    oPUId?: number;
}

/**
 * Check if a given object implements the LinesCreateReq interface.
 */
export function instanceOfLinesCreateReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LinesCreateReqFromJSON(json: any): LinesCreateReq {
    return LinesCreateReqFromJSONTyped(json, false);
}

export function LinesCreateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinesCreateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'oPUId': !exists(json, 'OPUId') ? undefined : json['OPUId'],
    };
}

export function LinesCreateReqToJSON(value?: LinesCreateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'OPUId': value.oPUId,
    };
}

