/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LocationsCreateReq
 */
export interface LocationsCreateReq {
    /**
     * 
     * @type {number}
     * @memberof LocationsCreateReq
     */
    parentStationId?: number;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateReq
     */
    name?: string;
}

/**
 * Check if a given object implements the LocationsCreateReq interface.
 */
export function instanceOfLocationsCreateReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LocationsCreateReqFromJSON(json: any): LocationsCreateReq {
    return LocationsCreateReqFromJSONTyped(json, false);
}

export function LocationsCreateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationsCreateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parentStationId': !exists(json, 'ParentStationId') ? undefined : json['ParentStationId'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function LocationsCreateReqToJSON(value?: LocationsCreateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ParentStationId': value.parentStationId,
        'Name': value.name,
    };
}

