/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    LocationsGetByIdResDetectorRes,
    instanceOfLocationsGetByIdResDetectorRes,
    LocationsGetByIdResDetectorResFromJSON,
    LocationsGetByIdResDetectorResFromJSONTyped,
    LocationsGetByIdResDetectorResToJSON,
} from './LocationsGetByIdResDetectorRes';

/**
 * @type LocationsGetByIdResDetector
 * 
 * @export
 */
export type LocationsGetByIdResDetector = LocationsGetByIdResDetectorRes;

export function LocationsGetByIdResDetectorFromJSON(json: any): LocationsGetByIdResDetector {
    return LocationsGetByIdResDetectorFromJSONTyped(json, false);
}

export function LocationsGetByIdResDetectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationsGetByIdResDetector {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...LocationsGetByIdResDetectorResFromJSONTyped(json, true) };
}

export function LocationsGetByIdResDetectorToJSON(value?: LocationsGetByIdResDetector | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfLocationsGetByIdResDetectorRes(value)) {
        return LocationsGetByIdResDetectorResToJSON(value as LocationsGetByIdResDetectorRes);
    }

    return {};
}

