/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocationsGetByIdResDetector } from './LocationsGetByIdResDetector';
import {
    LocationsGetByIdResDetectorFromJSON,
    LocationsGetByIdResDetectorFromJSONTyped,
    LocationsGetByIdResDetectorToJSON,
} from './LocationsGetByIdResDetector';

/**
 * 
 * @export
 * @interface LocationsGetByIdRes
 */
export interface LocationsGetByIdRes {
    /**
     * 
     * @type {number}
     * @memberof LocationsGetByIdRes
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LocationsGetByIdRes
     */
    name?: string;
    /**
     * 
     * @type {LocationsGetByIdResDetector}
     * @memberof LocationsGetByIdRes
     */
    detector?: LocationsGetByIdResDetector | null;
}

/**
 * Check if a given object implements the LocationsGetByIdRes interface.
 */
export function instanceOfLocationsGetByIdRes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LocationsGetByIdResFromJSON(json: any): LocationsGetByIdRes {
    return LocationsGetByIdResFromJSONTyped(json, false);
}

export function LocationsGetByIdResFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationsGetByIdRes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'detector': !exists(json, 'Detector') ? undefined : LocationsGetByIdResDetectorFromJSON(json['Detector']),
    };
}

export function LocationsGetByIdResToJSON(value?: LocationsGetByIdRes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
        'Detector': LocationsGetByIdResDetectorToJSON(value.detector),
    };
}

