/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectCoordinates
 */
export interface ObjectCoordinates {
    /**
     * 
     * @type {number}
     * @memberof ObjectCoordinates
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectCoordinates
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectCoordinates
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof ObjectCoordinates
     */
    height?: number;
}

/**
 * Check if a given object implements the ObjectCoordinates interface.
 */
export function instanceOfObjectCoordinates(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ObjectCoordinatesFromJSON(json: any): ObjectCoordinates {
    return ObjectCoordinatesFromJSONTyped(json, false);
}

export function ObjectCoordinatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectCoordinates {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'x': !exists(json, 'X') ? undefined : json['X'],
        'y': !exists(json, 'Y') ? undefined : json['Y'],
        'width': !exists(json, 'Width') ? undefined : json['Width'],
        'height': !exists(json, 'Height') ? undefined : json['Height'],
    };
}

export function ObjectCoordinatesToJSON(value?: ObjectCoordinates | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'X': value.x,
        'Y': value.y,
        'Width': value.width,
        'Height': value.height,
    };
}

