/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OPUsCreateReq
 */
export interface OPUsCreateReq {
    /**
     * 
     * @type {number}
     * @memberof OPUsCreateReq
     */
    parentSiteId?: number;
    /**
     * 
     * @type {string}
     * @memberof OPUsCreateReq
     */
    name?: string;
}

/**
 * Check if a given object implements the OPUsCreateReq interface.
 */
export function instanceOfOPUsCreateReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OPUsCreateReqFromJSON(json: any): OPUsCreateReq {
    return OPUsCreateReqFromJSONTyped(json, false);
}

export function OPUsCreateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): OPUsCreateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parentSiteId': !exists(json, 'ParentSiteId') ? undefined : json['ParentSiteId'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function OPUsCreateReqToJSON(value?: OPUsCreateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ParentSiteId': value.parentSiteId,
        'Name': value.name,
    };
}

