/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OPUsGetByIdResLineRes } from './OPUsGetByIdResLineRes';
import {
    OPUsGetByIdResLineResFromJSON,
    OPUsGetByIdResLineResFromJSONTyped,
    OPUsGetByIdResLineResToJSON,
} from './OPUsGetByIdResLineRes';

/**
 * 
 * @export
 * @interface OPUsGetByIdRes
 */
export interface OPUsGetByIdRes {
    /**
     * 
     * @type {number}
     * @memberof OPUsGetByIdRes
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof OPUsGetByIdRes
     */
    name?: string;
    /**
     * 
     * @type {Array<OPUsGetByIdResLineRes>}
     * @memberof OPUsGetByIdRes
     */
    lines?: Array<OPUsGetByIdResLineRes>;
}

/**
 * Check if a given object implements the OPUsGetByIdRes interface.
 */
export function instanceOfOPUsGetByIdRes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OPUsGetByIdResFromJSON(json: any): OPUsGetByIdRes {
    return OPUsGetByIdResFromJSONTyped(json, false);
}

export function OPUsGetByIdResFromJSONTyped(json: any, ignoreDiscriminator: boolean): OPUsGetByIdRes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'lines': !exists(json, 'Lines') ? undefined : ((json['Lines'] as Array<any>).map(OPUsGetByIdResLineResFromJSON)),
    };
}

export function OPUsGetByIdResToJSON(value?: OPUsGetByIdRes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
        'Lines': value.lines === undefined ? undefined : ((value.lines as Array<any>).map(OPUsGetByIdResLineResToJSON)),
    };
}

