/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OPUsRenameReq
 */
export interface OPUsRenameReq {
    /**
     * 
     * @type {string}
     * @memberof OPUsRenameReq
     */
    name?: string;
}

/**
 * Check if a given object implements the OPUsRenameReq interface.
 */
export function instanceOfOPUsRenameReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OPUsRenameReqFromJSON(json: any): OPUsRenameReq {
    return OPUsRenameReqFromJSONTyped(json, false);
}

export function OPUsRenameReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): OPUsRenameReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function OPUsRenameReqToJSON(value?: OPUsRenameReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
    };
}

