/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SitesCreateReq
 */
export interface SitesCreateReq {
    /**
     * 
     * @type {string}
     * @memberof SitesCreateReq
     */
    name?: string;
}

/**
 * Check if a given object implements the SitesCreateReq interface.
 */
export function instanceOfSitesCreateReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SitesCreateReqFromJSON(json: any): SitesCreateReq {
    return SitesCreateReqFromJSONTyped(json, false);
}

export function SitesCreateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitesCreateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function SitesCreateReqToJSON(value?: SitesCreateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
    };
}

