/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SitesListRes
 */
export interface SitesListRes {
    /**
     * 
     * @type {number}
     * @memberof SitesListRes
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SitesListRes
     */
    name?: string;
}

/**
 * Check if a given object implements the SitesListRes interface.
 */
export function instanceOfSitesListRes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SitesListResFromJSON(json: any): SitesListRes {
    return SitesListResFromJSONTyped(json, false);
}

export function SitesListResFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitesListRes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function SitesListResToJSON(value?: SitesListRes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
    };
}

