/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SitesGetByIdResResOPU } from './SitesGetByIdResResOPU';
import {
    SitesGetByIdResResOPUFromJSON,
    SitesGetByIdResResOPUFromJSONTyped,
    SitesGetByIdResResOPUToJSON,
} from './SitesGetByIdResResOPU';

/**
 * 
 * @export
 * @interface SitesGetByIdRes
 */
export interface SitesGetByIdRes {
    /**
     * 
     * @type {number}
     * @memberof SitesGetByIdRes
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SitesGetByIdRes
     */
    name?: string;
    /**
     * 
     * @type {Array<SitesGetByIdResResOPU>}
     * @memberof SitesGetByIdRes
     */
    oPUs?: Array<SitesGetByIdResResOPU>;
}

/**
 * Check if a given object implements the SitesGetByIdRes interface.
 */
export function instanceOfSitesGetByIdRes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SitesGetByIdResFromJSON(json: any): SitesGetByIdRes {
    return SitesGetByIdResFromJSONTyped(json, false);
}

export function SitesGetByIdResFromJSONTyped(json: any, ignoreDiscriminator: boolean): SitesGetByIdRes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'oPUs': !exists(json, 'OPUs') ? undefined : ((json['OPUs'] as Array<any>).map(SitesGetByIdResResOPUFromJSON)),
    };
}

export function SitesGetByIdResToJSON(value?: SitesGetByIdRes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
        'OPUs': value.oPUs === undefined ? undefined : ((value.oPUs as Array<any>).map(SitesGetByIdResResOPUToJSON)),
    };
}

