/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StationsCreateReq
 */
export interface StationsCreateReq {
    /**
     * 
     * @type {number}
     * @memberof StationsCreateReq
     */
    parentLineId?: number;
    /**
     * 
     * @type {string}
     * @memberof StationsCreateReq
     */
    name?: string;
}

/**
 * Check if a given object implements the StationsCreateReq interface.
 */
export function instanceOfStationsCreateReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StationsCreateReqFromJSON(json: any): StationsCreateReq {
    return StationsCreateReqFromJSONTyped(json, false);
}

export function StationsCreateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationsCreateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parentLineId': !exists(json, 'ParentLineId') ? undefined : json['ParentLineId'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function StationsCreateReqToJSON(value?: StationsCreateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ParentLineId': value.parentLineId,
        'Name': value.name,
    };
}

