/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TasksCreateReq
 */
export interface TasksCreateReq {
    /**
     * 
     * @type {number}
     * @memberof TasksCreateReq
     */
    parentJobId?: number;
    /**
     * 
     * @type {string}
     * @memberof TasksCreateReq
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof TasksCreateReq
     */
    locationId?: number;
}

/**
 * Check if a given object implements the TasksCreateReq interface.
 */
export function instanceOfTasksCreateReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TasksCreateReqFromJSON(json: any): TasksCreateReq {
    return TasksCreateReqFromJSONTyped(json, false);
}

export function TasksCreateReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksCreateReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parentJobId': !exists(json, 'ParentJobId') ? undefined : json['ParentJobId'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'locationId': !exists(json, 'LocationId') ? undefined : json['LocationId'],
    };
}

export function TasksCreateReqToJSON(value?: TasksCreateReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ParentJobId': value.parentJobId,
        'Name': value.name,
        'LocationId': value.locationId,
    };
}

