/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TaskInstanceFinalState = {
    Completed: 'Completed',
    Abandoned: 'Abandoned'
} as const;
export type TaskInstanceFinalState = typeof TaskInstanceFinalState[keyof typeof TaskInstanceFinalState];


export function TaskInstanceFinalStateFromJSON(json: any): TaskInstanceFinalState {
    return TaskInstanceFinalStateFromJSONTyped(json, false);
}

export function TaskInstanceFinalStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskInstanceFinalState {
    return json as TaskInstanceFinalState;
}

export function TaskInstanceFinalStateToJSON(value?: TaskInstanceFinalState | null): any {
    return value as any;
}

