/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TasksGetObjectsAndStepsResResObject } from './TasksGetObjectsAndStepsResResObject';
import {
    TasksGetObjectsAndStepsResResObjectFromJSON,
    TasksGetObjectsAndStepsResResObjectFromJSONTyped,
    TasksGetObjectsAndStepsResResObjectToJSON,
} from './TasksGetObjectsAndStepsResResObject';
import type { TasksGetObjectsAndStepsResResStep } from './TasksGetObjectsAndStepsResResStep';
import {
    TasksGetObjectsAndStepsResResStepFromJSON,
    TasksGetObjectsAndStepsResResStepFromJSONTyped,
    TasksGetObjectsAndStepsResResStepToJSON,
} from './TasksGetObjectsAndStepsResResStep';

/**
 * 
 * @export
 * @interface TasksGetObjectsAndStepsRes
 */
export interface TasksGetObjectsAndStepsRes {
    /**
     * 
     * @type {Array<TasksGetObjectsAndStepsResResObject>}
     * @memberof TasksGetObjectsAndStepsRes
     */
    objects?: Array<TasksGetObjectsAndStepsResResObject>;
    /**
     * 
     * @type {Array<TasksGetObjectsAndStepsResResStep>}
     * @memberof TasksGetObjectsAndStepsRes
     */
    steps?: Array<TasksGetObjectsAndStepsResResStep>;
}

/**
 * Check if a given object implements the TasksGetObjectsAndStepsRes interface.
 */
export function instanceOfTasksGetObjectsAndStepsRes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TasksGetObjectsAndStepsResFromJSON(json: any): TasksGetObjectsAndStepsRes {
    return TasksGetObjectsAndStepsResFromJSONTyped(json, false);
}

export function TasksGetObjectsAndStepsResFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksGetObjectsAndStepsRes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objects': !exists(json, 'Objects') ? undefined : ((json['Objects'] as Array<any>).map(TasksGetObjectsAndStepsResResObjectFromJSON)),
        'steps': !exists(json, 'Steps') ? undefined : ((json['Steps'] as Array<any>).map(TasksGetObjectsAndStepsResResStepFromJSON)),
    };
}

export function TasksGetObjectsAndStepsResToJSON(value?: TasksGetObjectsAndStepsRes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Objects': value.objects === undefined ? undefined : ((value.objects as Array<any>).map(TasksGetObjectsAndStepsResResObjectToJSON)),
        'Steps': value.steps === undefined ? undefined : ((value.steps as Array<any>).map(TasksGetObjectsAndStepsResResStepToJSON)),
    };
}

