/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TasksGetObjectsAndStepsResResObjectCoordinates } from './TasksGetObjectsAndStepsResResObjectCoordinates';
import {
    TasksGetObjectsAndStepsResResObjectCoordinatesFromJSON,
    TasksGetObjectsAndStepsResResObjectCoordinatesFromJSONTyped,
    TasksGetObjectsAndStepsResResObjectCoordinatesToJSON,
} from './TasksGetObjectsAndStepsResResObjectCoordinates';

/**
 * 
 * @export
 * @interface TasksGetObjectsAndStepsResResObject
 */
export interface TasksGetObjectsAndStepsResResObject {
    /**
     * 
     * @type {number}
     * @memberof TasksGetObjectsAndStepsResResObject
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TasksGetObjectsAndStepsResResObject
     */
    name?: string | null;
    /**
     * 
     * @type {TasksGetObjectsAndStepsResResObjectCoordinates}
     * @memberof TasksGetObjectsAndStepsResResObject
     */
    coordinates?: TasksGetObjectsAndStepsResResObjectCoordinates | null;
}

/**
 * Check if a given object implements the TasksGetObjectsAndStepsResResObject interface.
 */
export function instanceOfTasksGetObjectsAndStepsResResObject(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TasksGetObjectsAndStepsResResObjectFromJSON(json: any): TasksGetObjectsAndStepsResResObject {
    return TasksGetObjectsAndStepsResResObjectFromJSONTyped(json, false);
}

export function TasksGetObjectsAndStepsResResObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksGetObjectsAndStepsResResObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'coordinates': !exists(json, 'Coordinates') ? undefined : TasksGetObjectsAndStepsResResObjectCoordinatesFromJSON(json['Coordinates']),
    };
}

export function TasksGetObjectsAndStepsResResObjectToJSON(value?: TasksGetObjectsAndStepsResResObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
        'Coordinates': TasksGetObjectsAndStepsResResObjectCoordinatesToJSON(value.coordinates),
    };
}

