/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TasksDeleteReq
 */
export interface TasksDeleteReq {
    /**
     * 
     * @type {number}
     * @memberof TasksDeleteReq
     */
    parentJobId?: number;
}

/**
 * Check if a given object implements the TasksDeleteReq interface.
 */
export function instanceOfTasksDeleteReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TasksDeleteReqFromJSON(json: any): TasksDeleteReq {
    return TasksDeleteReqFromJSONTyped(json, false);
}

export function TasksDeleteReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksDeleteReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parentJobId': !exists(json, 'ParentJobId') ? undefined : json['ParentJobId'],
    };
}

export function TasksDeleteReqToJSON(value?: TasksDeleteReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ParentJobId': value.parentJobId,
    };
}

