/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TaskState } from './TaskState';
import {
    TaskStateFromJSON,
    TaskStateFromJSONTyped,
    TaskStateToJSON,
} from './TaskState';

/**
 * 
 * @export
 * @interface TasksGetByIdRes
 */
export interface TasksGetByIdRes {
    /**
     * 
     * @type {number}
     * @memberof TasksGetByIdRes
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TasksGetByIdRes
     */
    name?: string;
    /**
     * 
     * @type {TaskState}
     * @memberof TasksGetByIdRes
     */
    state?: TaskState;
}

/**
 * Check if a given object implements the TasksGetByIdRes interface.
 */
export function instanceOfTasksGetByIdRes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TasksGetByIdResFromJSON(json: any): TasksGetByIdRes {
    return TasksGetByIdResFromJSONTyped(json, false);
}

export function TasksGetByIdResFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksGetByIdRes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'state': !exists(json, 'State') ? undefined : TaskStateFromJSON(json['State']),
    };
}

export function TasksGetByIdResToJSON(value?: TasksGetByIdRes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
        'State': TaskStateToJSON(value.state),
    };
}

