/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplateState } from './TemplateState';
import {
    TemplateStateFromJSON,
    TemplateStateFromJSONTyped,
    TemplateStateToJSON,
} from './TemplateState';

/**
 * 
 * @export
 * @interface TasksUpdateReqNewStepReq
 */
export interface TasksUpdateReqNewStepReq {
    /**
     * 
     * @type {number}
     * @memberof TasksUpdateReqNewStepReq
     */
    orderNum?: number;
    /**
     * 
     * @type {TemplateState}
     * @memberof TasksUpdateReqNewStepReq
     */
    expectedInitialState?: TemplateState;
    /**
     * 
     * @type {TemplateState}
     * @memberof TasksUpdateReqNewStepReq
     */
    expectedSubsequentState?: TemplateState;
    /**
     * 
     * @type {string}
     * @memberof TasksUpdateReqNewStepReq
     */
    objectName?: string;
}

/**
 * Check if a given object implements the TasksUpdateReqNewStepReq interface.
 */
export function instanceOfTasksUpdateReqNewStepReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TasksUpdateReqNewStepReqFromJSON(json: any): TasksUpdateReqNewStepReq {
    return TasksUpdateReqNewStepReqFromJSONTyped(json, false);
}

export function TasksUpdateReqNewStepReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksUpdateReqNewStepReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderNum': !exists(json, 'OrderNum') ? undefined : json['OrderNum'],
        'expectedInitialState': !exists(json, 'ExpectedInitialState') ? undefined : TemplateStateFromJSON(json['ExpectedInitialState']),
        'expectedSubsequentState': !exists(json, 'ExpectedSubsequentState') ? undefined : TemplateStateFromJSON(json['ExpectedSubsequentState']),
        'objectName': !exists(json, 'ObjectName') ? undefined : json['ObjectName'],
    };
}

export function TasksUpdateReqNewStepReqToJSON(value?: TasksUpdateReqNewStepReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'OrderNum': value.orderNum,
        'ExpectedInitialState': TemplateStateToJSON(value.expectedInitialState),
        'ExpectedSubsequentState': TemplateStateToJSON(value.expectedSubsequentState),
        'ObjectName': value.objectName,
    };
}

