/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ObjectCoordinates } from './ObjectCoordinates';
import {
    ObjectCoordinatesFromJSON,
    ObjectCoordinatesFromJSONTyped,
    ObjectCoordinatesToJSON,
} from './ObjectCoordinates';

/**
 * 
 * @export
 * @interface TasksUpdateReqModObjectReq
 */
export interface TasksUpdateReqModObjectReq {
    /**
     * 
     * @type {number}
     * @memberof TasksUpdateReqModObjectReq
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TasksUpdateReqModObjectReq
     */
    name?: string;
    /**
     * 
     * @type {ObjectCoordinates}
     * @memberof TasksUpdateReqModObjectReq
     */
    coordinates?: ObjectCoordinates;
}

/**
 * Check if a given object implements the TasksUpdateReqModObjectReq interface.
 */
export function instanceOfTasksUpdateReqModObjectReq(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TasksUpdateReqModObjectReqFromJSON(json: any): TasksUpdateReqModObjectReq {
    return TasksUpdateReqModObjectReqFromJSONTyped(json, false);
}

export function TasksUpdateReqModObjectReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksUpdateReqModObjectReq {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'coordinates': !exists(json, 'Coordinates') ? undefined : ObjectCoordinatesFromJSON(json['Coordinates']),
    };
}

export function TasksUpdateReqModObjectReqToJSON(value?: TasksUpdateReqModObjectReq | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'Name': value.name,
        'Coordinates': ObjectCoordinatesToJSON(value.coordinates),
    };
}

