/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TaskInstanceFinalState,
    instanceOfTaskInstanceFinalState,
    TaskInstanceFinalStateFromJSON,
    TaskInstanceFinalStateFromJSONTyped,
    TaskInstanceFinalStateToJSON,
} from './TaskInstanceFinalState';

/**
 * @type TasksGetInstanceResResTaskInstanceFinalState
 * 
 * @export
 */
export type TasksGetInstanceResResTaskInstanceFinalState = TaskInstanceFinalState;

export function TasksGetInstanceResResTaskInstanceFinalStateFromJSON(json: any): TasksGetInstanceResResTaskInstanceFinalState {
    return TasksGetInstanceResResTaskInstanceFinalStateFromJSONTyped(json, false);
}

export function TasksGetInstanceResResTaskInstanceFinalStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksGetInstanceResResTaskInstanceFinalState {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...TaskInstanceFinalStateFromJSONTyped(json, true) };
}

export function TasksGetInstanceResResTaskInstanceFinalStateToJSON(value?: TasksGetInstanceResResTaskInstanceFinalState | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfTaskInstanceFinalState(value)) {
        return TaskInstanceFinalStateToJSON(value as TaskInstanceFinalState);
    }

    return {};
}

