/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TasksGetInstanceResResTaskInstance } from './TasksGetInstanceResResTaskInstance';
import {
    TasksGetInstanceResResTaskInstanceFromJSON,
    TasksGetInstanceResResTaskInstanceFromJSONTyped,
    TasksGetInstanceResResTaskInstanceToJSON,
} from './TasksGetInstanceResResTaskInstance';

/**
 * 
 * @export
 * @interface TasksGetInstanceRes
 */
export interface TasksGetInstanceRes {
    /**
     * 
     * @type {TasksGetInstanceResResTaskInstance}
     * @memberof TasksGetInstanceRes
     */
    instance?: TasksGetInstanceResResTaskInstance;
}

/**
 * Check if a given object implements the TasksGetInstanceRes interface.
 */
export function instanceOfTasksGetInstanceRes(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TasksGetInstanceResFromJSON(json: any): TasksGetInstanceRes {
    return TasksGetInstanceResFromJSONTyped(json, false);
}

export function TasksGetInstanceResFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksGetInstanceRes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instance': !exists(json, 'Instance') ? undefined : TasksGetInstanceResResTaskInstanceFromJSON(json['Instance']),
    };
}

export function TasksGetInstanceResToJSON(value?: TasksGetInstanceRes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Instance': TasksGetInstanceResResTaskInstanceToJSON(value.instance),
    };
}

