/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TaskState = {
    Active: 'Active',
    Paused: 'Paused',
    Inactive: 'Inactive'
} as const;
export type TaskState = typeof TaskState[keyof typeof TaskState];


export function TaskStateFromJSON(json: any): TaskState {
    return TaskStateFromJSONTyped(json, false);
}

export function TaskStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaskState {
    return json as TaskState;
}

export function TaskStateToJSON(value?: TaskState | null): any {
    return value as any;
}

