/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ObjectCoordinates,
    instanceOfObjectCoordinates,
    ObjectCoordinatesFromJSON,
    ObjectCoordinatesFromJSONTyped,
    ObjectCoordinatesToJSON,
} from './ObjectCoordinates';

/**
 * @type TasksGetObjectsAndStepsResResObjectCoordinates
 * 
 * @export
 */
export type TasksGetObjectsAndStepsResResObjectCoordinates = ObjectCoordinates;

export function TasksGetObjectsAndStepsResResObjectCoordinatesFromJSON(json: any): TasksGetObjectsAndStepsResResObjectCoordinates {
    return TasksGetObjectsAndStepsResResObjectCoordinatesFromJSONTyped(json, false);
}

export function TasksGetObjectsAndStepsResResObjectCoordinatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksGetObjectsAndStepsResResObjectCoordinates {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ObjectCoordinatesFromJSONTyped(json, true) };
}

export function TasksGetObjectsAndStepsResResObjectCoordinatesToJSON(value?: TasksGetObjectsAndStepsResResObjectCoordinates | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfObjectCoordinates(value)) {
        return ObjectCoordinatesToJSON(value as ObjectCoordinates);
    }

    return {};
}

