/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    TaskType,
    instanceOfTaskType,
    TaskTypeFromJSON,
    TaskTypeFromJSONTyped,
    TaskTypeToJSON,
} from './TaskType';

/**
 * @type TasksUpdateReqNewType
 * 
 * @export
 */
export type TasksUpdateReqNewType = TaskType;

export function TasksUpdateReqNewTypeFromJSON(json: any): TasksUpdateReqNewType {
    return TasksUpdateReqNewTypeFromJSONTyped(json, false);
}

export function TasksUpdateReqNewTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksUpdateReqNewType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...TaskTypeFromJSONTyped(json, true) };
}

export function TasksUpdateReqNewTypeToJSON(value?: TasksUpdateReqNewType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfTaskType(value)) {
        return TaskTypeToJSON(value as TaskType);
    }

    return {};
}

