/* tslint:disable */
/* eslint-disable */
/**
 * dotnet-nswag
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TasksGetInstanceResResEvent } from './TasksGetInstanceResResEvent';
import {
    TasksGetInstanceResResEventFromJSON,
    TasksGetInstanceResResEventFromJSONTyped,
    TasksGetInstanceResResEventToJSON,
} from './TasksGetInstanceResResEvent';
import type { TasksGetInstanceResResTaskInstanceFinalState } from './TasksGetInstanceResResTaskInstanceFinalState';
import {
    TasksGetInstanceResResTaskInstanceFinalStateFromJSON,
    TasksGetInstanceResResTaskInstanceFinalStateFromJSONTyped,
    TasksGetInstanceResResTaskInstanceFinalStateToJSON,
} from './TasksGetInstanceResResTaskInstanceFinalState';

/**
 * 
 * @export
 * @interface TasksGetInstanceResResTaskInstance
 */
export interface TasksGetInstanceResResTaskInstance {
    /**
     * 
     * @type {number}
     * @memberof TasksGetInstanceResResTaskInstance
     */
    id?: number;
    /**
     * 
     * @type {TasksGetInstanceResResTaskInstanceFinalState}
     * @memberof TasksGetInstanceResResTaskInstance
     */
    finalState?: TasksGetInstanceResResTaskInstanceFinalState | null;
    /**
     * 
     * @type {Array<TasksGetInstanceResResEvent>}
     * @memberof TasksGetInstanceResResTaskInstance
     */
    events?: Array<TasksGetInstanceResResEvent> | null;
    /**
     * 
     * @type {number}
     * @memberof TasksGetInstanceResResTaskInstance
     */
    taskId?: number;
}

/**
 * Check if a given object implements the TasksGetInstanceResResTaskInstance interface.
 */
export function instanceOfTasksGetInstanceResResTaskInstance(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TasksGetInstanceResResTaskInstanceFromJSON(json: any): TasksGetInstanceResResTaskInstance {
    return TasksGetInstanceResResTaskInstanceFromJSONTyped(json, false);
}

export function TasksGetInstanceResResTaskInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksGetInstanceResResTaskInstance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'Id') ? undefined : json['Id'],
        'finalState': !exists(json, 'FinalState') ? undefined : TasksGetInstanceResResTaskInstanceFinalStateFromJSON(json['FinalState']),
        'events': !exists(json, 'Events') ? undefined : (json['Events'] === null ? null : (json['Events'] as Array<any>).map(TasksGetInstanceResResEventFromJSON)),
        'taskId': !exists(json, 'TaskId') ? undefined : json['TaskId'],
    };
}

export function TasksGetInstanceResResTaskInstanceToJSON(value?: TasksGetInstanceResResTaskInstance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Id': value.id,
        'FinalState': TasksGetInstanceResResTaskInstanceFinalStateToJSON(value.finalState),
        'Events': value.events === undefined ? undefined : (value.events === null ? null : (value.events as Array<any>).map(TasksGetInstanceResResEventToJSON)),
        'TaskId': value.taskId,
    };
}

